# Change these first
owner: noclocks
repo: uptime

sites:
  - name: Domain
    url: https://noclocks.dev
  - name: Website
    url: https://noclocks.dev
  - name: Online Store
    url: https://store.noclocks.dev
  - name: Development Store
    url: https://devstore.noclocks.dev
  - name: Blog
    url: https://blog.noclocks.dev
  - name: Medium
    url: https://medium.noclocks.dev/
  - name: Testimonials
    url: https://testimonials.noclocks.dev
  - name: EnvShare
    url: https://envshare.noclocks.dev
  - name: DevDocs (Demo)
    url: https://devdocs.noclocks.dev

assignees:
  - jimbrig
  - phoward38

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: docs.noclocks.dev
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Uptime
  introTitle: "**No Clocks Uptime Monitor**"
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/noclocks/uptime).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
